import type { TCanvasNodeOptions } from "@/nodes/types";

export const DEFAULT_CONFIG_CONTROL_EDITION_2D: TCanvasNodeOptions["2D/control-edition"] =
	{
		opacity: 1,
		background: "#fff",
		border: true,
		borderColor: "#eee",
		borderWidth: 1,
		centerRotation: true,
		centerScale: true,
		cornerBorder: true,
		cornerColor: "blue",
		cornerColorBorder: "red",
		cornerSize: 2,
		cursor: "default",
		description: "",
		flipX: false,
		flipY: false,
		height: 0,
		width: 0,
		lock: false,
		originX: "center",
		originY: "center",
		padding: 10,
		radius: 0,
		rotation: 0,
		scaleX: 1,
		scaleY: 1,
		selectable: true,
		showCorner: true,
		skewX: 1,
		skewY: 1,
		title: "",
		visible: true,
		x: 0,
		y: 0,
		hovered: true,
	};
