import type { TCanvasNodeOptions } from "@/nodes/types";

export const DEFAULT_CONFIG_SELECTION_2D: TCanvasNodeOptions["2D/selection"] = {
	alpha: 1,
	background: "#000",
	border: true,
	borderColor: "#eee",
	borderWidth: 1,
	cursor: "default",
	description: "",
	endX: 0,
	endY: 0,
	flipX: false,
	flipY: false,
	height: 100,
	width: 100,
	lock: false,
	originX: "center",
	originY: "center",
	radius: 0,
	rotation: 0,
	scaleX: 1,
	scaleY: 1,
	selectable: true,
	shape: "rectangle",
	skewX: 0,
	skewY: 0,
	startX: 0,
	startY: 0,
	title: "",
	visible: true,
	x: 0,
	y: 0,
	hovered: true,
};
