import { IOptionsNodeControlEdition } from "../../../basic/nodes/types"

export const DEFAULT_CONFIG_NODE_CONTROL_EDITION: IOptionsNodeControlEdition = {
  rotation: 0,
  cursor: "default",
  deep: "0",
  height: 10,
  name: "Node2D",
  origin: "center",
  originX: "center",
  originY: "center",
  centerRotation: true,
  centerScale: true,
  scale: 1,
  scaleX: 1,
  scaleY: 1,
  skew: 1,
  skewX: 1,
  skewY: 1,
  visible: true,
  lock: false,
  selectable: true,
  width: 10,
  flipX: false,
  flipY: false,
  x: 0,
  y: 0,
  borderColor: "",
  cornerBorder: true,
  cornerColor: "",
  cornerColorBorder: "",
  cornerSize: 10,
  padding: 0,
  showCorner: true
}
