import { IOptionsNodeText } from "../../../basic/nodes/types"

export const DEFAULT_CONFIG_NODE_TEXT: IOptionsNodeText = {
  rotation: 0,
  cursor: "default",
  deep: "0",
  height: 0,
  name: "NodeText",
  origin: "center",
  originX: "center",
  originY: "center",
  centerRotation: true,
  centerScale: true,
  scale: 1,
  scaleX: 1,
  scaleY: 1,
  skew: 1,
  skewX: 1,
  skewY: 1,
  visible: true,
  width: 0,
  x: 0,
  y: 0,
  fontFamily: "system-ui",
  fontSize: "0px",
  fontStretch: "normal",
  fontStyle: "normal",
  fontVariant: "normal",
  fontWeight: "normal",
  lineHeight: "normal",
  textBaseline: "alphabetic",
  textDirection: "ltr",
  text: "",
  textAlign: "left",
  border: false,
  borderColor: "",
  borderWidth: 0,
  color: "black",
  wordSpacing: "0px",
  letterSpacing: "0px",
  flipX: false,
  flipY: false,
  lock: false,
  selectable: true
}
