export const PropFunctions = Symbol("PropFunctions")
export const PropAttributes = Symbol("PropAttributes")
export const PropMetaKeys = Symbol("PropMetaKeys")
export const PropNodes = Symbol("PropNodes")
export const PropComponents = Symbol("PropComponents")
export const PropType = Symbol("PropType")
export const PropCollider = Symbol("PropCollider")

export const MethodSetParent = Symbol("MethodSetParent")
export const MethodSetIndex = Symbol("MethodSetIndex")
export const MethodSetId = Symbol("MethodSetId")
export const MethodSetAttributes = Symbol("MethodSetAttributes")
export const MethodSetComponents = Symbol("MethodSetComponents")
export const MethodSetFunctions = Symbol("MethodSetFunctions")
export const MethodSetMetaKeys = Symbol("MethodSetMetaKeys")
export const MethodSetNodes = Symbol("MethodSetNodes")
