import type { TCanvasNodeOptions } from "@/nodes/types";

export const DEFAULT_CONFIG_TEXT_2D: TCanvasNodeOptions["2D/text"] = {
	alpha: 1,
	rotation: 0,
	cursor: "default",
	height: 0,
	originX: "center",
	originY: "center",
	position: "Vec2(0, 0)",
	scale: "Vec2(1, 1)",
	skew: "Vec2(0, 0)",
	visible: true,
	width: 0,
	fontFamily: "system-ui",
	fontSize: "12px",
	fontStretch: "normal",
	fontStyle: "normal",
	fontVariant: "normal",
	fontWeight: "normal",
	textBaseline: "alphabetic",
	textDirection: "ltr",
	text: "Atomic Engine",
	textAlign: "left",
	fill: "#000000",
	stroke: "",
	lineWidth: 0,
	flipX: false,
	flipY: false,
	lock: false,
	selectable: true,
	title: "",
	description: "",
	hovered: true,
	compositeOperation: "source-over"
};
