import { IOptionsNodeRectangle } from "../../../basic/nodes/types"

export const DEFAULT_CONFIG_NODE_RECTANGLE: IOptionsNodeRectangle = {
  rotation: 0,
  cursor: "default",
  deep: "0",
  height: 100,
  name: "NodeRectangle",
  origin: "center",
  originX: "center",
  originY: "center",
  angleOrigin: "center",
  angleOriginX: "center",
  angleOriginY: "center",
  scaleOrigin: "center",
  scaleOriginX: "center",
  scaleOriginY: "center",
  translateOrigin: "center",
  translateOriginX: "center",
  translateOriginY: "center",
  scale: 1,
  scaleX: 1,
  scaleY: 1,
  skew: 1,
  skewX: 1,
  skewY: 1,
  visible: true,
  width: 100,
  x: 0,
  y: 0,
  background: "black",
  border: false,
  borderColor: "",
  borderWidth: 0,
  radius: 0
}
