import { IOptionsScene2D } from "../../../basic/nodes/types";

export const DEFAULT_CONFIG_SCENE_2D: IOptionsScene2D = {
    rotation: 0,
    cursor: "default",
    deep: "0",
    height: 1000,
    name: "Scene2D",
    origin: "center",
    originX: "center",
    originY: "center",
    angleOrigin: "center",
    angleOriginX: "center",
    angleOriginY: "center",
    scaleOrigin: "center",
    scaleOriginX: "center",
    scaleOriginY: "center",
    translateOrigin: "center",
    translateOriginX: "center",
    translateOriginY: "center",
    scale: 1,
    scaleX: 1,
    scaleY: 1,
    skew: 1,
    skewX: 1,
    skewY: 1,
    visible: true,
    width: 1000,
    x: 0,
    y: 0,
}
