import { IOptionsNodeSelection } from "../../../basic/nodes/types"

export const DEFAULT_CONFIG_NODE_SELECTION: IOptionsNodeSelection = {
    rotation: 0,
    cursor: "default",
    deep: "0",
    height: 0,
    name: "NodeSelection",
    origin: "center",
    originX: "center",
    originY: "center",
    angleOrigin: "center",
    angleOriginX: "center",
    angleOriginY: "center",
    scaleOrigin: "center",
    scaleOriginX: "center",
    scaleOriginY: "center",
    translateOrigin: "center",
    translateOriginX: "center",
    translateOriginY: "center",
    scale: 1,
    scaleX: 1,
    scaleY: 1,
    skew: 1,
    skewX: 1,
    skewY: 1,
    visible: true,
    width: 0,
    x: 0,
    y: 0,
    background: "black",
    border: false,
    borderColor: "",
    borderWidth: 0,
    radius: 0,
    endX: 0,
    endY: 0,
    startX: 0,
    startY: 0,
    type: "rectangle",
}
