import type { TCanvasNodeOptions } from "@/nodes/types";

export const DEFAULT_CONFIG_LINE_FLOW_EFFECT_2D: TCanvasNodeOptions["2D/line-flow-effect"] =
{
	alpha: 1,
	cursor: "default",
	visible: true,
	lock: false,
	selectable: true,
	cellSize: 15,
	lineWidth: 5,
	spacing: 5,
	radius: 0,
	color: "white",
	description: "",
	title: "",
	rotation: 0,
	height: 10,
	originX: "center",
	originY: "center",
	scaleX: 1,
	scaleY: 1,
	skewX: 0,
	skewY: 0,
	width: 10,
	flipX: false,
	flipY: false,
	x: 0,
	y: 0,
	hovered: true,
};
