import type { TCanvasNodeOptions } from "@/nodes/types";

export const DEFAULT_CONFIG_CIRCLE_2D: TCanvasNodeOptions["2D/circle"] = {
    alpha: 1,
    rotation: 0,
    cursor: "default",
    height: 60,
    description: "",
    title: "",
    originX: "center",
    originY: "center",
    position: "Vec2(0, 0)",
    scale: "Vec2(1, 1)",
    skew: "Vec2(0, 0)",
    visible: true,
    width: 60,
    fill: "#000000",
    stroke: "",
    lineWidth: 0,
    radius: 30,
    flipX: false,
    flipY: false,
    lock: false,
    selectable: true,
    hovered: true,
    counterclockwise: false,
    startAngle: 0,
    endAngle: Math.PI * 2,
    compositeOperation: "source-over"
};
