import type { TCanvasNodeOptions } from "@/nodes/types";

export const DEFAULT_CONFIG_CIRCLE_2D: TCanvasNodeOptions["2D/circle"] = {
    alpha: 1,
    rotation: 0,
    cursor: "default",
    height: 100,
    description: "",
    title: "",
    originX: "center",
    originY: "center",
    scaleX: 1,
    scaleY: 1,
    skewX: 0,
    skewY: 0,
    visible: true,
    width: 100,
    x: 0,
    y: 0,
    background: "black",
    border: false,
    borderColor: "",
    borderWidth: 0,
    radius: 30,
    flipX: false,
    flipY: false,
    lock: false,
    selectable: true,
    hovered: true,
    counterclockwise: false,
    startAngle: 0,
    endAngle: Math.PI * 2,
};
